[package]
name = "scrapr"
version = "0.1.0"
authors = ["Pawel Rynowiecki <pawel.rynowiecki@anixe.pl>"]
edition = "2018"

[dependencies]
scraper = "0.11.0"
easy-http-request = "0.2.5"
itertools = "0.8.2"
rand = "0.7.2"